import type { Metadata } from "next";
import { Gideon_Roman, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Contact from "./components/Contact";

const inter = Inter({ subsets: ["latin"]})
const gideon = Gideon_Roman({ subsets: ["latin"], weight: "400"  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={gideon.className}>
        <Navbar />
          {children}
      </body>
    </html>
  );
}
